    name: Deploy Frontend
    on:
      push:
        branches:
          - main # check your repo, your default branch might be master!
     
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          - run: docker build -t whiz4kid/react-test -f Dockerfile.dev .
          - run: docker run -e CI=true whiz4kid/react-test npm test
     
          - name: Generate deployment package
            run: zip -r deploy.zip . -x '*.git*'
     
          - name: Deploy to EB
            uses: prepatdiscobj/docker-react-test@v0
            with:
              aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
              aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
              application_name: docker-react-test-app
              environment_name: Docker-react-test-app-env
              existing_bucket_name: elasticbeanstalk-ap-southeast-2-325997912167
              region: ap-southeast-2
              version_label: ${{ github.sha }}
              deployment_package: deploy.zip